### ISSUE TITLE
Role Assignment

### ISSUE THREAD

**Issue by jordanx9** [jordanx9/fleetManager#6]
PUT /api/users/:id/role
      ✓ should update user role as admin (2 ms)
      ✕ should return 403 if not admin (5 ms)
      ✕ should return 404 if user not found (1 ms)
      ✕ should return 400 for invalid role (1 ms)
      ✕ should return 500 if a database error occurs (2 ms)

`● User Routes › PUT /api/users/:id/role › should return 403 if not admin

    expect(received).toBe(expected) // Object.is equality

    Expected: 403
    Received: 500

      416 |         .send({ role: 'Driver' });
      417 |   
    > 418 |       expect(res.statusCode).toBe(403);
          |                              ^
      419 |       expect(res.body).toHaveProperty('error', 'Not authorized');
      420 |   
      421 |       // Restore the original middleware

      at Object.toBe (backend/_tests_/userRoutes.test.js:418:30)

  ● User Routes › PUT /api/users/:id/role › should return 404 if user not found

    expect(received).toBe(expected) // Object.is equality

    Expected: 404
    Received: 500

      431 |         .send({ role: 'Driver' });
      432 |   
    > 433 |       expect(res.statusCode).toBe(404);
          |                              ^
      434 |       expect(res.body).toHaveProperty('error', 'User not found');
      435 |     });
      436 |   

      at Object.toBe (backend/_tests_/userRoutes.test.js:433:30)

  ● User Routes › PUT /api/users/:id/role › should return 400 for invalid role

    expect(received).toBe(expected) // Object.is equality

    Expected: 400
    Received: 500

      441 |         .send({ role: 'InvalidRole' });
      442 |   
    > 443 |       expect(res.statusCode).toBe(400);
          |                              ^
      444 |       expect(res.body).toHaveProperty('errors');
      445 |     });
      446 |   

      at Object.toBe (backend/_tests_/userRoutes.test.js:443:30)

  ● User Routes › PUT /api/users/:id/role › should return 500 if a database error occurs

    expect(received).toHaveProperty(path, value)

    Expected path: "error"
    Received path: []

    Expected value: "Server error"
    Received value: {}

      454 |   
      455 |       expect(res.statusCode).toBe(500);
    > 456 |       expect(res.body).toHaveProperty('error', 'Server error');
          |                        ^
      457 |     });
      458 |   });
      459 | });

      at Object.toHaveProperty (backend/_tests_/userRoutes.test.js:456:24)`

**Comment by jordanx9** [comment]
Accidentally assigned all types of users to admin....... fixed.
